import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Helvetica Neue", "Helvetica", "Arial", "sans-serif"],
        "bo-sans": ["var(--font-bo-sans)", "var(--font-bo-sans-jp, ui-sans-serif)", "system-ui", "sans-serif"],
        "bo-serif": ["var(--font-bo-serif)", "var(--font-bo-serif-jp, ui-serif)", "Georgia", "serif"],
      },
      colors: {
        cream: "#F5F0E8",
        "cream-dark": "#EDE8DE",
        brown: {
          DEFAULT: "#3D2B1F",
          light: "#6B4A35",
          dark: "#1A0F08",
        },
        gold: "#C9A96E",
        "warm-gray": "#8C7B6B",
        // Back-office v3 — variables sémantiques « MDB » (voir src/app/admin/admin.css)
        bo: {
          app: "var(--color-bg-app)",
          surface: "var(--color-bg-surface)",
          subtle: "var(--color-bg-subtle)",
          muted: "var(--color-bg-muted)",
          sidebar: "var(--color-bg-sidebar)",
          "sidebar-active": "rgb(58 45 36 / <alpha-value>)",
          primary: "var(--color-bg-primary)",
          "primary-hover": "var(--color-bg-primary-hover)",
          overlay: "rgb(36 26 20 / <alpha-value>)",
          toast: "var(--color-bg-toast)",
          line: "var(--color-border-default)",
          "line-strong": "var(--color-border-strong)",
          focus: "var(--color-border-focus)",
          "line-danger": "rgb(184 65 47 / <alpha-value>)",
          "line-sidebar": "var(--color-border-sidebar)",
          ink: "var(--color-text-primary)",
          "ink-2": "var(--color-text-secondary)",
          "ink-3": "var(--color-text-tertiary)",
          "ink-disabled": "var(--color-text-disabled)",
          "ink-inverse": "var(--color-text-inverse)",
          "ink-sidebar": "var(--color-text-sidebar)",
          "ink-sidebar-muted": "var(--color-text-sidebar-muted)",
          "ink-accent": "var(--color-text-accent)",
          "ink-danger": "var(--color-text-danger)",
          icon: "var(--color-icon-default)",
          accent: "var(--color-accent-default)",
          "accent-subtle": "var(--color-accent-subtle)",
          "success-bg": "var(--color-status-success-bg)",
          success: "var(--color-status-success-fg)",
          "info-bg": "var(--color-status-info-bg)",
          info: "var(--color-status-info-fg)",
          "warning-bg": "var(--color-status-warning-bg)",
          warning: "var(--color-status-warning-fg)",
          "danger-bg": "var(--color-status-danger-bg)",
          danger: "var(--color-status-danger-fg)",
          "neutral-bg": "var(--color-status-neutral-bg)",
          neutral: "var(--color-status-neutral-fg)",
          "chip-green-bg": "var(--color-chip-green-bg)",
          "chip-green": "var(--color-chip-green-fg)",
          "chip-blue-bg": "var(--color-chip-blue-bg)",
          "chip-blue": "var(--color-chip-blue-fg)",
          "chip-brown-bg": "var(--color-chip-brown-bg)",
          "chip-brown": "var(--color-chip-brown-fg)",
          "chip-red-bg": "var(--color-chip-red-bg)",
          "chip-red": "var(--color-chip-red-fg)",
          "chip-cream-bg": "var(--color-chip-cream-bg)",
          "chip-cream": "var(--color-chip-cream-fg)",
          "chip-cream-line": "var(--color-chip-cream-border)",
        },
      },
      letterSpacing: {
        widest: "0.2em",
        ultrawide: "0.3em",
      },
      borderRadius: {
        "bo-sm": "6px",
        "bo-md": "8px",
        "bo-lg": "12px",
        "bo-xl": "16px",
      },
      boxShadow: {
        "bo-xs": "0 1px 2px rgba(36, 26, 20, 0.06)",
        "bo-md": "0 4px 12px rgba(36, 26, 20, 0.08), 0 1px 3px rgba(36, 26, 20, 0.05)",
        "bo-lg": "0 16px 40px rgba(36, 26, 20, 0.18), 0 2px 6px rgba(36, 26, 20, 0.06)",
        "bo-focus": "0 0 0 3px rgba(176, 138, 74, 0.35)",
        "bo-focus-danger": "0 0 0 3px rgba(184, 64, 46, 0.2)",
      },
      fontSize: {
        // Les titres serif sont réduits de 15 % en japonais via --bo-serif-scale
        "bo-display": ["calc(34px * var(--bo-serif-scale, 1))", { lineHeight: "40px", letterSpacing: "-0.005em" }],
        "bo-display-s": ["calc(28px * var(--bo-serif-scale, 1))", { lineHeight: "34px", letterSpacing: "-0.005em" }],
        "bo-brand": ["calc(20px * var(--bo-serif-scale, 1))", { lineHeight: "24px" }],
        "bo-kpi": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em" }],
        "bo-heading": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em" }],
        "bo-card": ["15px", { lineHeight: "22px", letterSpacing: "-0.005em" }],
        "bo-body": ["14px", { lineHeight: "20px", letterSpacing: "-0.005em" }],
        "bo-small": ["13px", { lineHeight: "18px", letterSpacing: "-0.003em" }],
        "bo-caption": ["12px", { lineHeight: "16px" }],
      },
    },
  },
  plugins: [],
};

export default config;
